In [ ]:
import pandas as pd
import unicodedata

In [16]:
def remove_acentos(texto):
    return unicodedata.normalize('NFKD', texto).encode('ASCII', 'ignore').decode('ASCII').lower()

'sao jose do rio preto'

In [21]:
df = pd.read_csv('../../data/raw/lista_mestra_campi.csv')
df_br = df[df['pais'] == 'BR']

In [39]:
df_br = df_br[~df_br['municipio'].isna()].reset_index(drop=True)

In [40]:
df_br['municipio_key'] = df_br['municipio'].apply(remove_acentos)

In [11]:
df_ibge = pd.read_csv('../../data/raw/outputs_extraction/ibge_municipios.csv')

In [44]:
df_ibge['municipio_key'] = df_ibge['nome_municipio'].apply(remove_acentos)

In [45]:
df_br.merge(df_ibge, on='municipio_key', how='left')

,campus_id,pais,lat,lon,n_predios,nome,operadora,municipio,uf,ano_operacional,...,va_servicos,va_industria,va_agropecuaria,impostos_liquidos,pct_va_servicos,pct_va_industria,pct_va_agropecuaria,pct_impostos,latitude,longitude
0,br-0001,BR,-23.571264,-46.619437,2,Data Center Marechal Rondon,Brazilian Army,Sao Paulo,NaN,2015.0,...,4.633770e+11,6.064669e+10,43867000.0,1.171066e+11,0.6784,0.0888,0.0001,0.1714,-23.567386,-46.570383
1,br-0001,BR,-23.571264,-46.619437,2,Data Center Marechal Rondon,Brazilian Army,Sao Paulo,NaN,2015.0,...,4.747870e+11,5.864282e+10,37649000.0,1.225261e+11,0.6793,0.0839,0.0001,0.1753,-23.567386,-46.570383
2,br-0001,BR,-23.571264,-46.619437,2,Data Center Marechal Rondon,Brazilian Army,Sao Paulo,NaN,2015.0,...,4.853954e+11,5.806499e+10,36420000.0,1.271570e+11,0.6792,0.0812,0.0001,0.1779,-23.567386,-46.570383
3,br-0001,BR,-23.571264,-46.619437,2,Data Center Marechal Rondon,Brazilian Army,Sao Paulo,NaN,2015.0,...,5.284041e+11,5.713071e+10,41808000.0,1.324751e+11,0.6920,0.0748,0.0001,0.1735,-23.567386,-46.570383
4,br-0001,BR,-23.571264,-46.619437,2,Data Center Marechal Rondon,Brazilian Army,Sao Paulo,NaN,2015.0,...,5.191612e+11,5.743942e+10,61896000.0,1.243296e+11,0.6951,0.0769,0.0001,0.1665,-23.567386,-46.570383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,br-0112,BR,-21.835768,-41.044137,1,Yamna Porto do Açu,Yamna,São João da Barra,NaN,NaN,...,3.458850e+09,3.627401e+09,43292000.0,4.035570e+08,0.4340,0.4552,0.0054,0.0506,-21.639031,-41.051018
929,br-0112,BR,-21.835768,-41.044137,1,Yamna Porto do Açu,Yamna,São João da Barra,NaN,NaN,...,3.403198e+09,2.148418e+09,52106000.0,4.626210e+08,0.5265,0.3324,0.0081,0.0716,-21.639031,-41.051018
930,br-0112,BR,-21.835768,-41.044137,1,Yamna Porto do Açu,Yamna,São João da Barra,NaN,NaN,...,4.061567e+09,4.636444e+09,59304000.0,7.139900e+08,0.4108,0.4690,0.0060,0.0722,-21.639031,-41.051018
931,br-0112,BR,-21.835768,-41.044137,1,Yamna Porto do Açu,Yamna,São João da Barra,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21.639031,-41.051018
932,br-0112,BR,-21.835768,-41.044137,1,Yamna Porto do Açu,Yamna,São João da Barra,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21.639031,-41.051018

In [ ]:
df_resultado = adicionar_cidades_similares(df_input, features, modo_regiao="mesma", n_similares=3)

In [9]:
df_br

,campus_id,pais,lat,lon,n_predios,nome,operadora,municipio,uf,ano_operacional,fonte,origem_data,no_estudo_atual,tem_data
0,br-0001,BR,-23.571264,-46.619437,2,Data Center Marechal Rondon,Brazilian Army,Sao Paulo,NaN,2015.0,datacentermap,declarada_datacentermap,False,True
1,br-0002,BR,-22.706501,-43.237432,1,ADA Rio de Janeiro,Ada Infrastructure,Duque de Caxias,NaN,NaN,datacentermap,NaN,False,False
2,br-0003,BR,-30.016502,-51.203888,10,Adentro DC Porto Alegre,ADENTRO DATA CENTER SOLUTIONS LTDA,Porto Alegre,Rio Grande do Sul,2023.0,datacentermap,declarada_datacentermap,True,True
3,br-0004,BR,-18.920915,-48.309049,1,Algar Tech Uberlandia - Jaraguá,Algar Tech,Uberlandia,MG,NaN,datacentermap,NaN,False,False
4,br-0005,BR,-18.872513,-48.245163,1,Algar Tech Uberlandia - Granja Marileusa,Algar Tech,Uberlandia,Minas Gerais,NaN,datacentermap,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,br-0120,BR,-23.033745,-44.548543,1,Datacenter de Mambucaba,Eletronuclear,NaN,NaN,NaN,osm,NaN,False,False
120,br-0121,BR,-22.228678,-50.892422,3,Fleetnet,NaN,NaN,NaN,NaN,osm,NaN,False,False
121,br-0122,BR,-21.758339,-41.317588,1,Centro de Dirigentes Lojistas de Campos dos Go...,CDL,NaN,NaN,NaN,osm,NaN,False,False
122,br-0123,BR,-19.929033,-43.978629,1,Data Center (Ministério Público de Minas Gerais),NaN,NaN,NaN,NaN,osm,NaN,False,False
123,br-0124,BR,-10.893398,-37.064276,2,NaN,NaN,NaN,NaN,NaN,osm,NaN,False,False

In [ ]:
# Depois em outro codigo, na parte de transformação peguei os a fonte de cidades similares data\silver\municipios_com_cidades_similares.csv
# junte as cidades similares com dados do ibge e tire uma media para os indicadores ( o que é melhor? media ou mediana? veja o que é melhor e apique, só depois me fale o que aplicou) salve essa transformação na camada silver.

SyntaxError: invalid syntax (3265292884.py, line 1)